#
# Module manifest for module 'PSGet_Microsoft365QuickStart'
#
# Generated by: Andreas Krüger
#
# Generated on: 14.04.2020
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'Modules\Microsoft365QuickStart\Microsoft365QuickStart.psm1'

    # Version number of this module.
    ModuleVersion     = '1.0.0.0'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID              = 'fc605f3f-5372-4230-b96f-f59cf427b6e8'

    # Author of this module
    Author            = 'Andreas Krüger'

    # Company or vendor of this module
    CompanyName       = 'SoftwareONE'

    # Copyright statement for this module
    Copyright         = '(c) Andreas Krüger. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'This module provides a set of functions to enable basic and restrive settings for Microsoft 365 tenants.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules   = @(
        @{
            ModuleName      = 'Microsoft365DSC'
            RequiredVersion = '1.0.4.39'
        },
        @{
            ModuleName      = "SharePointPnPPowerShellOnline"
            RequiredVersion = "3.20.2004.0"
        },
        @{
            ModuleName      = "Microsoft.Online.SharePoint.PowerShell"
            RequiredVersion = "16.0.19515.12000"
        },
        @{
            ModuleName      = "MicrosoftTeams"
            RequiredVersion = "1.0.5"
        },
        @{
            ModuleName      = "AzureADPreview"
            RequiredVersion = "2.0.2.89"
        },
        @{
            ModuleName      = "MSCloudLoginAssistant"
            RequiredVersion = "1.0.6"
        },
        @{
            ModuleName      = "Microsoft.PowerApps.Administration.PowerShell"
            RequiredVersion = "2.0.56"
        }
    )

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules     = @('Modules\MSCommerceAlpha\MSCommerceAlpha.psd1')

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @('Set-Microsoft365QuickStartTemplate')

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = ''

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = 'Office 365', 'SharePoint Online', 'OneDrive', 'Microsoft Teams', 'Governance'

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/TenantStarterKits/Microsoft365QuickStart/blob/master/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/TenantStarterKits/Microsoft365QuickStart'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

            # External dependent modules of this module
            # ExternalModuleDependencies = ''

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

